/*=========================================================================

Program:   RVA
Module:    ISATISReader

Copyright (c) University of Illinois at Urbana-Champaign (UIUC)
Original Authors: L Angrave, J Duggirala, D McWherter, U Yadav

All rights reserved.
See Copyright.txt for details.

This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#ifndef __ISATISGUIPANEL_H_
#define __ISATISGUIPANEL_H_

#include "pqAutoGeneratedObjectPanel.h"

class ISATISReaderSource;
class pqProxy;
class QWidget;
class QComboBox;
class QLineEdit;
class QPushButton;
class QLabel;

class ISATISGUIPanel : public pqAutoGeneratedObjectPanel {
  Q_OBJECT

public slots:
  void UpdateStudyCombo();
  void UpdateDirectoryCombo();
  void UpdateFileListCombo();
  void SetFile();
  void SetLengthUnit();
  void ForceReload();
  void UpdateStatusMessage();

public:
  ISATISGUIPanel(pqProxy* pxy, QWidget *q);
  virtual ~ISATISGUIPanel();

  void SetupComboBoxes();
  void SetupTextBoxes();
  void InitializeLengthUnitsCombo();
  void UpdatePreferences();
  void CheckPreferences();

private:
  ISATISReaderSource * Reader;
  QPushButton * RefreshButton;
  QLineEdit * StatusLabel;
  QLineEdit * HostEdit, * PortEdit, * PathEdit;
  QComboBox * StudyListCombo, * DirectoryListCombo, * FileListCombo, * LengthUnitsCombo;
};


#endif // __ISATISGUIPANEL_H_
